### ISSUE TITLE
Some issues are popping up.

### ISSUE THREAD

**Issue by farishkash** [craftykate/jammming#1]
So first a couple screenshots

![jamming](https://user-images.githubusercontent.com/5844161/33328248-56747f26-d40e-11e7-8eb1-deb836c9c8cf.jpg)

Console Errors below

![2](https://user-images.githubusercontent.com/5844161/33328251-58a21d8a-d40e-11e7-8f20-7356894e91e8.jpg)

The first one is the more important one.  I had notice that you are using

`scope=playlist-modify-private`

The problem here is that you need additional scoping in this case.

![authorize_-_spotify](https://user-images.githubusercontent.com/5844161/33328853-f6f59e48-d40f-11e7-9652-11ef12e1f39f.jpg)

`playlist-read-private`

https://developer.spotify.com/web-api/using-scopes/

I don't see that being requested and I think that it is needed. 

The project was built with the idea that 

`playlist-modify-public` would be used because there is no additional scoping needed since public playlists are meant to be open to all.

**Comment by craftykate** [comment]
Thanks, I changed playlist back to public. Do you get any errors on your end now?

**Comment by farishkash** [comment]
It worked, no errors.

**Comment by craftykate** [comment]
Thanks for reviewing!
