### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by farishkash** [craftykate/jammming#2]
Overall met expectations.

Interesting that you made separate functions for the fetch Get and the fetch Post requests.  Good job in doing that, I think it is clearer in some regards.

Code overall was well structured and readable.  I saw no major issues.  The issue I did mention is a common one when using private playlists.

**Comment by craftykate** [comment]
Thanks! I felt pulling out fetch Get and fetch Post made the functions that use them much simpler and more straightforward in their purpose - and figuring how to refactor them that way was great practice with fetch requests and promises.
